#ifndef CALIB_MODE_HOST_DEVICE
    #define CALIB_MODE_HOST_DEVICE

    #define CALIB_N_THREADS_PER_BLOCK 1024
    #define CALIB_MAX_ALLOWED_CONCURRENT_STREAMS 5
    #define CALIB_FACTORIAL_TABLE_SIZE 50
#endif